import Head from 'next/head';
import FAQ from '../components/FAQ/FAQ';

export default function FAQPage() {
  return (
    <>
      <Head>
        <title>
          Meet Our Doctors | Best Family Dentists in Summerlin, Las Vegas
        </title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <FAQ />
    </>
  );
}
