import Head from 'next/head';
import HomeBanner from '../components/HomeBanner';

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          Lake Mead Dental | Home | Best Family Dentists in Summerlin, Las Vegas
        </title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/apple-touch-icon.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/favicon-32x32.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='16x16'
          href='/favicon-16x16.png'
        />
        <link rel='manifest' href='/site.webmanifest' />
      </Head>
      <HomeBanner />
    </div>
  );
}
