import Head from 'next/head';
import TreatmentsPageComponent from '../components/TreatmentsPageComponent/TreatmentsPageComponent';

export default function TreatmentsPage() {
  return (
    <>
      <Head>
        <title>
          Our Treatments | Best Family Dentists in Summerlin, Las Vegas
        </title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <TreatmentsPageComponent />
    </>
  );
}
